[package]
name = "Assignment2_SSS_VSS"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.6", features = ["rand"] }
num-prime = "0.4.4"
num-traits = "0.2.19"
rand = "0.8.5"
sha2 = "0.10.8"
